services:
  backend:
    build:
      context: ./backend
    ports:
      - "8100:8100"
    restart: unless-stopped
    networks:
      - learnda

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - learnda

networks:
  learnda:
    driver: bridge
