services:
  backend:
    build:
      context: ./backend
    expose:
      - "8100"
    restart: unless-stopped
    networks:
      - learnda

  frontend:
    build:
      context: ./frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - learnda

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    extra_hosts:
      - "host-gateway:host-gateway"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - learnda

networks:
  learnda:
    driver: bridge