server {
    listen 80;
    server_name learn-da.com www.learn-da.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name learn-da.com www.learn-da.com;

    ssl_certificate /etc/letsencrypt/live/learn-da.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/learn-da.com/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8100/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /teda/ {
        proxy_pass http://172.17.0.1:8000/teda/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /teda/assets/ {
        proxy_pass http://172.17.0.1:8000/teda/assets/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}