server {
    listen 80;
    server_name learn-da.com www.learn-da.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name learn-da.com www.learn-da.com;

    ssl_certificate /etc/letsencrypt/live/learn-da.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/learn-da.com/privkey.pem;

    location /api/ {
        proxy_pass http://backend:8100/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name teda.learn-da.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name teda.learn-da.com;

    ssl_certificate /etc/letsencrypt/live/teda.learn-da.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/teda.learn-da.com/privkey.pem;

    location /api/ {
        proxy_pass http://172.17.0.1:8001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
        chunked_transfer_encoding on;
    }

    location / {
        proxy_pass http://172.17.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}